// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTat-cQ1UyoUx0xiULpYhHYimMWcKWJu4',
    appId: '1:315166682344:web:8775ae67e920f25b4ead5d',
    messagingSenderId: '315166682344',
    projectId: 'preflight-crew-auth-stan',
    authDomain: 'preflight-crew-auth-stan.firebaseapp.com',
    storageBucket: 'preflight-crew-auth-stan.firebasestorage.app',
    measurementId: 'G-PZ8CZBHK6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEYOzHEXe0F45TyxPb4WdCgUTJEUNCa8',
    appId: '1:315166682344:android:7375a11df1d185274ead5d',
    messagingSenderId: '315166682344',
    projectId: 'preflight-crew-auth-stan',
    storageBucket: 'preflight-crew-auth-stan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrqI_cckJHuaOtHQfLpl8Xp1zJxADvNY',
    appId: '1:315166682344:ios:04873e7b0ff06fff4ead5d',
    messagingSenderId: '315166682344',
    projectId: 'preflight-crew-auth-stan',
    storageBucket: 'preflight-crew-auth-stan.firebasestorage.app',
    iosBundleId: 'co.za.wethinkcode.preflightCrewAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrqI_cckJHuaOtHQfLpl8Xp1zJxADvNY',
    appId: '1:315166682344:ios:04873e7b0ff06fff4ead5d',
    messagingSenderId: '315166682344',
    projectId: 'preflight-crew-auth-stan',
    storageBucket: 'preflight-crew-auth-stan.firebasestorage.app',
    iosBundleId: 'co.za.wethinkcode.preflightCrewAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTat-cQ1UyoUx0xiULpYhHYimMWcKWJu4',
    appId: '1:315166682344:web:9ec1c4e023745cf14ead5d',
    messagingSenderId: '315166682344',
    projectId: 'preflight-crew-auth-stan',
    authDomain: 'preflight-crew-auth-stan.firebaseapp.com',
    storageBucket: 'preflight-crew-auth-stan.firebasestorage.app',
    measurementId: 'G-4PSSEK7QCN',
  );
}
